// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SA2.Data;

#nullable disable

namespace SA2.Migrations
{
    [DbContext(typeof(AlunoDbContext))]
    [Migration("20260322180221_MoverIdENomeParaUser")]
    partial class MoverIdENomeParaUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SA2.Classes.Entidades.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RegistroAluno")
                        .HasColumnType("int");

                    b.Property<string>("StatusAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusWifi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CursoId = 1,
                            Nome = "Clodoaldo",
                            RegistroAluno = 1001,
                            StatusAction = "Aprovado",
                            StatusWifi = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            CursoId = 2,
                            Nome = "César",
                            RegistroAluno = 1002,
                            StatusAction = "Aguardando aprovação",
                            StatusWifi = "Inativo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
